<a href="https://colab.research.google.com/github/2403a51l53/2403A51L53_BATCH_52/blob/main/Lab%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Question 1
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B:\n", add_result)
print("\nA - B:\n", sub_result)

print("\nVerification for element [0,0]:")
print(f"A[0,0] = {A[0,0]}, B[0,0] = {B[0,0]}")
print(f"Addition: {A[0,0]} + {B[0,0]} = {add_result[0,0]}")
print(f"Subtraction: {A[0,0]} - {B[0,0]} = {sub_result[0,0]}")

print("\nNote: Broadcasting is not used here since both matrices are of the same shape (3x3).")

Matrix A:
 [[ 9  2 10]
 [ 7  6  9]
 [ 4  4  2]]

Matrix B:
 [[ 2  2  5]
 [ 9  2 10]
 [10 10  1]]

A + B:
 [[11  4 15]
 [16  8 19]
 [14 14  3]]

A - B:
 [[ 7  0  5]
 [-2  4 -1]
 [-6 -6  1]]

Verification for element [0,0]:
A[0,0] = 9, B[0,0] = 2
Addition: 9 + 2 = 11
Subtraction: 9 - 2 = 7

Note: Broadcasting is not used here since both matrices are of the same shape (3x3).
